name: Build Documentations
on:
  push:
    branches:
      - master
    paths-ignore:
      - "bot/**"
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-docs:
    name: build-docs
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: docs
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: DocFX Build
        working-directory: ./docs
        run: docfx docfx.json
        continue-on-error: false
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          cname: intern.gnztmpz.eu.org
