name: Lint
on: pull_request

jobs:
  Lint:
    # Check if the PR is not raised by this workflow and is not from a fork
    if: startsWith(github.head_ref, 'black-patches') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Actions
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Lint with Black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --diff --verbose --target-version py310"
      - name: Set branch name
        if: steps.action_black.outputs.is_formatted == 'true'
        run: echo ::set-output name=branch-name::"black-patches/${{ github.head_ref }}"
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          git config --global user.name 'GNZTMPZ2'
          git config --global user.email '85807297+GNZTMPZ2@users.noreply.github.com'
          git commit -am "Automated black fixes"
          git push