name: PR Lint
on: 
  pull_request:
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Actions
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Lint with Black
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --diff --verbose --target-version py310"